export enum DossierStatus {
  AWAITING_DOSSIER_GENERATION = 'AWAITING_DOSSIER_GENERATION',
  EMAIL_ERROR = 'EMAIL_ERROR',
  EMAIL_SENT = 'EMAIL_SENT',
  EXPIRED_EMAIL = 'EXPIRED_EMAIL',
  GENERATED_DOSSIER = 'GENERATED_DOSSIER'
}
