stages:
  - build
  - test
  - deploy

build:
  tags:
    - front
  stage: build
  image: docker-nexus.uds.com.br/node:16-alpine
  artifacts:
    paths:
      - dist/
    expire_in: 1 hrs
  cache:
    paths:
      - node_modules/
  only:
    - /^develop$/
    - /^master$/
    - /^.*-quality$/
    - /^.*-release$/
    - /^.*-production$/
    - merge_requests
  script:
    - npm install
    - npm run build

test:
  tags:
    - front
  stage: test
  image: docker-nexus.uds.com.br/node:16-alpine
  only: ['merge_requests']
  except:
    - /^develop$/
    - /^release/\d+.*/
    - /^master$/
  dependencies:
    - build
  script:
    - npm install
    - npm run test:coverage

deploy-develop:
  stage: deploy
  image:
    name: docker-nexus.uds.com.br/tmaier/docker-compose:latest
    entrypoint: ["/bin/sh", "-c"]
  only:
    - /^develop$/
  script:
    - export API_HOST=$API_HOST_DEVELOP
    - export ELASTIC_HOST=$ELASTIC_HOST_DEVELOP
    - export ELASTIC_USER=$ELASTIC_USER_DEVELOP
    - export ELASTIC_PASSWORD=$ELASTIC_PASSWORD_DEVELOP
    - export AWS_S3_BUCKET=$AWS_S3_BUCKET
    - export AWS_S3_ACCESS_KEY=$AWS_S3_ACCESS_KEY
    - export AWS_S3_KEY_SECRET=$AWS_S3_KEY_SECRET
    - export REDIS_HOST=$REDIS_HOST_DEVELOP
    - export REDIS_PASSWORD=$REDIS_PASSWORD_DEVELOP
    - export REDIS_PORT=$REDIS_PORT_DEVELOP
    - export COGNITO_REGION=$COGNITO_REGION_DEVELOP
    - export COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID_DEVELOP
    - export COGNITO_USER_APP_CLIENT_ID=$COGNITO_USER_APP_CLIENT_ID_DEVELOP
    - export COGNITO_DOMAIN=$COGNITO_DOMAIN_DEVELOP
    - docker login docker-nexus.uds.com.br -u $DOCKER_USER -p $DOCKER_PASSWORD
    - export JOB_PORTAL_URL=$JOB_PORTAL_URL_DEVELOP
    - export GRAYLOG_HOST=$GRAYLOG_HOST
    - export GRAYLOG_PORT=$GRAYLOG_PORT
    - docker build --build-arg API_HOST=$API_HOST --build-arg AWS_S3_BUCKET=$AWS_S3_BUCKET --build-arg AWS_S3_ACCESS_KEY=$AWS_S3_ACCESS_KEY --build-arg  AWS_S3_KEY_SECRET=$AWS_S3_KEY_SECRET --build-arg  REDIS_HOST=$REDIS_HOST --build-arg  REDIS_PASSWORD=$REDIS_PASSWORD --build-arg  REDIS_PORT=$REDIS_PORT --build-arg ELASTIC_HOST=$ELASTIC_HOST --build-arg ELASTIC_USER=$ELASTIC_USER --build-arg ELASTIC_PASSWORD=$ELASTIC_PASSWORD --build-arg COGNITO_REGION=$COGNITO_REGION --build-arg COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID --build-arg COGNITO_USER_APP_CLIENT_ID=$COGNITO_USER_APP_CLIENT_ID --build-arg COGNITO_DOMAIN=$COGNITO_DOMAIN --build-arg JOB_PORTAL_URL=$JOB_PORTAL_URL --build-arg GRAYLOG_HOST=$GRAYLOG_HOST --build-arg GRAYLOG_PORT=$GRAYLOG_PORT --no-cache=$IGNORAR_DOCKER_CACHE -t docker-nexus.uds.com.br/swrecruiter/backend:develop .
    - echo $API_HOST 
    - docker push docker-nexus.uds.com.br/swrecruiter/backend:develop
  tags:
    - front
    
deploy-quality:
  stage: deploy
  image:
    name: docker-nexus.uds.com.br/tmaier/docker-compose:latest
    entrypoint: ["/bin/sh", "-c"]
  only:
    - /^.*-quality$/
  script:  
    - export API_HOST=$API_HOST_QUALITY 
    - export ELASTIC_HOST=$ELASTIC_HOST_QUALITY
    - export ELASTIC_USER=$ELASTIC_USER_QUALITY
    - export ELASTIC_PASSWORD=$ELASTIC_PASSWORD_QUALITY
    - export AWS_S3_BUCKET=$AWS_S3_BUCKET
    - export AWS_S3_ACCESS_KEY=$AWS_S3_ACCESS_KEY
    - export AWS_S3_KEY_SECRET=$AWS_S3_KEY_SECRET
    - export REDIS_HOST=$REDIS_HOST_QUALITY
    - export REDIS_PASSWORD=$REDIS_PASSWORD_QUALITY
    - export REDIS_PORT=$REDIS_PORT_QUALITY
    - export COGNITO_REGION=$COGNITO_REGION_QUALITY
    - export COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID_QUALITY
    - export COGNITO_USER_APP_CLIENT_ID=$COGNITO_USER_APP_CLIENT_ID_QUALITY
    - export COGNITO_DOMAIN=$COGNITO_DOMAIN_QUALITY
    - export JOB_PORTAL_URL=$JOB_PORTAL_URL_QUALITY
    - export GRAYLOG_HOST=$GRAYLOG_HOST
    - export GRAYLOG_PORT=$GRAYLOG_PORT
    - docker login docker-nexus.uds.com.br -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build --build-arg API_HOST=$API_HOST --build-arg AWS_S3_BUCKET=$AWS_S3_BUCKET --build-arg AWS_S3_ACCESS_KEY=$AWS_S3_ACCESS_KEY --build-arg  AWS_S3_KEY_SECRET=$AWS_S3_KEY_SECRET --build-arg REDIS_HOST=$REDIS_HOST --build-arg  REDIS_PASSWORD=$REDIS_PASSWORD --build-arg  REDIS_PORT=$REDIS_PORT --build-arg ELASTIC_HOST=$ELASTIC_HOST --build-arg ELASTIC_USER=$ELASTIC_USER --build-arg ELASTIC_PASSWORD=$ELASTIC_PASSWORD --build-arg COGNITO_REGION=$COGNITO_REGION --build-arg COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID --build-arg COGNITO_USER_APP_CLIENT_ID=$COGNITO_USER_APP_CLIENT_ID --build-arg COGNITO_DOMAIN=$COGNITO_DOMAIN --build-arg JOB_PORTAL_URL=$JOB_PORTAL_URL --build-arg GRAYLOG_HOST=$GRAYLOG_HOST --build-arg GRAYLOG_PORT=$GRAYLOG_PORT --no-cache=$IGNORAR_DOCKER_CACHE -t docker-nexus.uds.com.br/swrecruiter/backend:quality .
    - echo $API_HOST
    - docker push docker-nexus.uds.com.br/swrecruiter/backend:quality
  tags:
    - front

deploy-production:
  stage: deploy
  image:
    name: docker-nexus.uds.com.br/tmaier/docker-compose:latest
    entrypoint: ["/bin/sh", "-c"]
  only:
    - /^.*-production$/
  script:
    - export API_HOST=$API_HOST_PRODUCTION
    - export ELASTIC_HOST=$ELASTIC_HOST_PRODUCTION
    - export ELASTIC_USER=$ELASTIC_USER_PRODUCTION
    - export ELASTIC_PASSWORD=$ELASTIC_PASSWORD_PRODUCTION
    - echo $API_HOST 
    - export AWS_S3_BUCKET=$AWS_S3_BUCKET
    - export AWS_S3_ACCESS_KEY=$AWS_S3_ACCESS_KEY
    - export AWS_S3_KEY_SECRET=$AWS_S3_KEY_SECRET
    - export REDIS_HOST=$REDIS_HOST_PRODUCTION
    - export REDIS_PASSWORD=$REDIS_PASSWORD_PRODUCTION
    - export REDIS_PORT=$REDIS_PORT_PRODUCTION
    - export COGNITO_REGION=$COGNITO_REGION_PRODUCTION
    - export COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID_PRODUCTION
    - export COGNITO_USER_APP_CLIENT_ID=$COGNITO_USER_APP_CLIENT_ID_PRODUCTION
    - export COGNITO_DOMAIN=$COGNITO_DOMAIN_PRODUCTION
    - export JOB_PORTAL_URL=$JOB_PORTAL_URL_PRODUCTION
    - export GRAYLOG_HOST=$GRAYLOG_HOST
    - export GRAYLOG_PORT=$GRAYLOG_PORT
    - docker login docker-nexus.uds.com.br -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build --build-arg API_HOST=$API_HOST --build-arg AWS_S3_BUCKET=$AWS_S3_BUCKET --build-arg AWS_S3_ACCESS_KEY=$AWS_S3_ACCESS_KEY --build-arg  AWS_S3_KEY_SECRET=$AWS_S3_KEY_SECRET --build-arg REDIS_HOST=$REDIS_HOST --build-arg  REDIS_PASSWORD=$REDIS_PASSWORD --build-arg  REDIS_PORT=$REDIS_PORT --build-arg ELASTIC_HOST=$ELASTIC_HOST --build-arg ELASTIC_USER=$ELASTIC_USER --build-arg ELASTIC_PASSWORD=$ELASTIC_PASSWORD --build-arg COGNITO_REGION=$COGNITO_REGION --build-arg COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID --build-arg COGNITO_USER_APP_CLIENT_ID=$COGNITO_USER_APP_CLIENT_ID --build-arg COGNITO_DOMAIN=$COGNITO_DOMAIN --build-arg JOB_PORTAL_URL=$JOB_PORTAL_URL --build-arg GRAYLOG_HOST=$GRAYLOG_HOST --build-arg GRAYLOG_PORT=$GRAYLOG_PORT --no-cache=$IGNORAR_DOCKER_CACHE -t docker-nexus.uds.com.br/swrecruiter/backend:production .
    - docker push docker-nexus.uds.com.br/swrecruiter/backend:production
  tags:
    - front 