FROM docker-nexus.uds.com.br/starter-kit/node:18-alpine

ARG API_HOST
ARG AWS_S3_BUCKET
ARG AWS_S3_ACCESS_KEY
ARG AWS_S3_KEY_SECRET
ARG REDIS_PASSWORD
ARG REDIS_HOST
ARG REDIS_PORT
ARG ELASTIC_HOST
ARG ELASTIC_USER
ARG ELASTIC_PASSWORD
ARG GRAYLOG_HOST
ARG GRAYLOG_PORT

ENV API_URL=${API_HOST}
ENV AWS_S3_BUCKET=${AWS_S3_BUCKET}
ENV AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
ENV AWS_S3_KEY_SECRET=${AWS_S3_KEY_SECRET}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV ELASTIC_HOST=${ELASTIC_HOST}
ENV ELASTIC_USER=${ELASTIC_USER}
ENV ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
ENV GRAYLOG_HOST=${GRAYLOG_HOST}
ENV GRAYLOG_PORT=${GRAYLOG_PORT}

ARG COGNITO_REGION
ARG COGNITO_USER_POOL_ID
ARG COGNITO_USER_APP_CLIENT_ID
ARG COGNITO_DOMAIN

ENV COGNITO_REGION=${COGNITO_REGION}
ENV COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
ENV COGNITO_USER_APP_CLIENT_ID=${COGNITO_USER_APP_CLIENT_ID}

ARG JOB_PORTAL_URL
ENV JOB_PORTAL_URL=${JOB_PORTAL_URL}
ENV COGNITO_DOMAIN=${COGNITO_DOMAIN}

WORKDIR /opt/backend

COPY ./package.json ./
COPY ./tsconfig.json ./
COPY ./tsconfig.build.json ./
COPY ./src/config/typeorm ./src/config/typeorm

RUN echo $API_HOST
RUN export API_URL=$API_HOST
RUN export AWS_S3_BUCKET=$AWS_S3_BUCKET
RUN export AWS_S3_ACCESS_KEY=$AWS_S3_ACCESS_KEY
RUN export AWS_S3_KEY_SECRET=$AWS_S3_KEY_SECRET
RUN export REDIS_PASSWORD=$REDIS_PASSWORD
RUN export REDIS_HOST=$REDIS_HOST
RUN export REDIS_PORT=$REDIS_PORT
RUN export ELASTIC_HOST=$ELASTIC_HOST
RUN export ELASTIC_USER=$ELASTIC_USER
RUN export ELASTIC_PASSWORD=$ELASTIC_PASSWORD
RUN export COGNITO_REGION=$COGNITO_REGION
RUN export COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID
RUN export COGNITO_USER_APP_CLIENT_ID=$COGNITO_USER_APP_CLIENT_ID
RUN export COGNITO_DOMAIN=$COGNITO_DOMAIN
RUN export JOB_PORTAL_URL=$JOB_PORTAL_URL
RUN export GRAYLOG_HOST=$GRAYLOG_HOST
RUN export GRAYLOG_PORT=$GRAYLOG_PORT

RUN yarn --ignore-engines
RUN mkdir dist

#RUN npm run migration:run
RUN npm run build

COPY ./dist/ ./dist/
CMD npm run start:prod
